version: '3.3'
services:
  registry:
    image: registry:2
    environment:
      VIRTUAL_HOST: registry.<domain>.com
      VIRTUAL_PORT: '5000'
    ports:
     - 5000:5000
    networks:
     - public
    logging:
      driver: json-file
networks:
  public:
    external: true
